### ISSUE TITLE
Doesn't work "[STDERR: input.scriptfilter] env: node: No such file or directory"

### ISSUE THREAD

**Issue by kokarn** [aviaryan/alfred-clc#2]
Did exactly as told

```
brew install insect
```

`insect` works fine in terminal.

Running `clc 2+4` does nothing.

In the debug for clc it just gives 
```
[STDERR: input.scriptfilter] env: node: No such file or directory
```
over and over.

**Comment by aviaryan** [comment]
@kokarn Just updated the workflow. Can you please try again?

**Comment by kokarn** [comment]
Fixed with latest version. Thanks!
