### ISSUE TITLE
Insect not found but...

### ISSUE THREAD

**Issue by ytarakji** [aviaryan/alfred-clc#3]
Hi, I'm setting up my new Macbook Pro M1Pro 
I installed brew normally and then used brew to install insect.
it works from the terminal as expected but the workflow doesn't see it. 
sorry to ask this but is this something to do with brew installing stuff in a different location?
I fixed it by typing in the terminal:
`which insect`
and it gave me this:
`/opt/homebrew/bin/insect`
which then I ended up editing clc "run.sh" to use that path: and it worked but what gives?
![image](https://user-images.githubusercontent.com/31030392/143420286-715cd8b3-51a6-49c4-8252-52fb9ab3fe78.png)
if I would have installed insect from npm would it have worked then?

**Comment by aviaryan** [comment]
I can't say for sure. Looks like they changed the default homebrew `bin` directory for M1 Macs, that is why it failed. Not sure where `npm install -g` installs binaries on an M1 Mac since I don't have it yet.
Why don't you try it?

**Comment by ytarakji** [comment]
I learned that on apple silicon, homebrew install stuff in this directory by default `/opt/homebrew/bin` 
anyway, it's working for me now I just had to change this one line. 

I did have a similar issue with another workflow "Spotify_Mini_Player" same thing the path was different, but there were a ton of paths to edit so instead I downloaded a fresh copy of the workflow, and when I installed that instead of the one  I had installed from an old version I have downloaded a while ago it picked up the right path.

**Comment by nik312123** [comment]
This issue was not really resolved as it requires the workflow's users to manually edit the `run.sh` file. I made [another issue](https://github.com/aviaryan/alfred-clc/issues/5) that can probably be merged into this one at some point, and I made a [pull request](https://github.com/aviaryan/alfred-clc/pull/4) that resolves this issue.
